# Generated by Django 3.1.7 on 2021-04-06 08:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_facility_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='testimonial',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
