# Generated by Django 3.1.7 on 2021-03-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210313_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_days',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
